### PR TITLE
Point at staticmap service at openstreetmap.de

### PR DESCRIPTION
**Pull request by stephankn**
seems to work fine with https and a referrer of wiki.openstreetmap.org.

### CODE REVIEW

**Comment by Tigerfell** [comment]
I would use HTTPS since both the wiki and the tile stitching service use HSTS.

**Comment by stephankn** [comment]
@Tigerfell absolutely. I tested only with HTTPS. I did not pay enough attention when switching over the service. Thanks for pointing this out.

**Comment by harry-wood** [comment]
So someone set-up https on staticmap.openstreetmap.de hey? (This old discussion https://github.com/fossgis/openstreetmap.de/issues/25 ) .  I see that working, except... 

now the image generation is not working coming with black images (even when it is getting a referrer):

https://harrywood.co.uk/maps/examples/static-image/staticmaplite.html

Screenshot 2020-12-07 at 00 32 58

**Comment by stephankn** [comment]
I manually called "https://staticmap.openstreetmap.de/staticmap.php?center=40.714728,-73.998672&zoom=14&size=865x512&maptype=mapnik" with a referrer. Then it returned a static map image. So I thought it will simply work.

I checked with different coordinates and get the same results you did. I hope @giggls can comment on what goes on with the server. Wikimedia support might not come back, see #4

**Comment by stephankn** [comment]
I opened an issue at fossgis. https://github.com/fossgis/openstreetmap.de/issues/36

Would it be possible to create static maps directly on wiki.openstreetmap.org?

**Comment by giggls** [comment]
https://staticmap.openstreetmap.de is a highly abused service and basically more or less unmaintained.
@woodpeck did the current install. I would be glad if this service would be gone from our community server.

**Comment by Firefishy** [comment]
Closing as no longer required as SimpleMap has now been removed from wiki.

**Pull request closed without merging**
